-- Table: Clients
CREATE TABLE Clients (
    Client_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Type VARCHAR2(10) CHECK (Type IN ('Member', 'Guest')) NOT NULL,
    Relationship VARCHAR2(50),
    Contact VARCHAR2(15) NOT NULL,
    Emergency_Contact VARCHAR2(15),
    Email VARCHAR2(100) UNIQUE,
    Address CLOB
);

-- Table: Membership
CREATE TABLE Membership (
    Membership_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Client_ID NUMBER NOT NULL,
    Plan_Type VARCHAR2(10) CHECK (Plan_Type IN ('Silver', 'Gold', 'Platinum')) NOT NULL,
    Start_Date DATE NOT NULL,
    End_Date DATE NOT NULL,
    Status VARCHAR2(10) CHECK (Status IN ('Active', 'Inactive')) NOT NULL,
    Price NUMBER(10, 2) NOT NULL
);

-- Table: Fitness Classes
CREATE TABLE Fitness_Classes (
    Class_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Type VARCHAR2(10) CHECK (Type IN ('Yoga', 'Pilates', 'HIIT', 'Spinning')) NOT NULL,
    Schedule TIMESTAMP NOT NULL,
    Instructor_ID NUMBER NOT NULL,
    Max_Capacity NUMBER NOT NULL
);

-- Table: Class Bookings
CREATE TABLE Class_Bookings (
    Booking_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Class_ID NUMBER NOT NULL,
    Client_ID NUMBER NOT NULL,
    Status VARCHAR2(15) CHECK (Status IN ('Confirmed', 'Canceled', 'Waitlisted')) NOT NULL
);

-- Table: Training
CREATE TABLE Training (
    Training_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Client_ID NUMBER NOT NULL,
    Trainer_ID NUMBER NOT NULL,
    Session_Date TIMESTAMP NOT NULL,
    Workout_Details CLOB
);

-- Table: Health Assessments
CREATE TABLE Health_Assessments (
    Assessment_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Client_ID NUMBER NOT NULL,
    Trainer_ID NUMBER NOT NULL,
    Assessment_Date DATE NOT NULL,
    Weight NUMBER(5, 2),
    BMI NUMBER(5, 2),
    Body_Fat_Percentage NUMBER(5, 2)
);

-- Table: Gym Attendance
CREATE TABLE Gym_Attendance (
    Attendance_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Client_ID NUMBER NOT NULL,
    Attendance_Date DATE NOT NULL,
    Check_in TIMESTAMP NOT NULL,
    Check_out TIMESTAMP,
    Facility VARCHAR2(100) NOT NULL
);

-- Table: Billing
CREATE TABLE Billing (
    Billing_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Client_ID NUMBER NOT NULL,
    Amount NUMBER(10, 2) NOT NULL,
    Billing_Date DATE NOT NULL,
    Payment_Method VARCHAR2(15) CHECK (Payment_Method IN ('Credit Card', 'Debit Card', 'Cash', 'Direct Debit')) NOT NULL,
    Discount_Applied CHAR(1) DEFAULT 'N' CHECK (Discount_Applied IN ('Y', 'N')),
    Discount_Amount NUMBER(10, 2) DEFAULT 0.00
);

-- Table: Discounts
CREATE TABLE Discounts (
    Discount_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Type VARCHAR2(15) CHECK (Type IN ('Promotion', 'Referral')) NOT NULL,
    Code VARCHAR2(20) UNIQUE NOT NULL,
    Usage_Count NUMBER DEFAULT 0,
    Revenue_Loss NUMBER(10, 2) DEFAULT 0.00
);

-- Table: Staff
CREATE TABLE Staff (
    Staff_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Role VARCHAR2(15) CHECK (Role IN ('Trainer', 'Instructor', 'Admin')) NOT NULL,
    Specialization VARCHAR2(50),
    Contact VARCHAR2(15),
    Emergency_Contact VARCHAR2(15),
    Salary NUMBER(10, 2)
);

-- Table: Facilities
CREATE TABLE Facilities (
    Facility_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Location VARCHAR2(100) NOT NULL
);

-- Table: Equipment Rentals
CREATE TABLE Equipment_Rentals (
    Rental_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Equipment_ID NUMBER NOT NULL,
    Client_ID NUMBER NOT NULL,
    Rental_Date DATE NOT NULL,
    Return_Date DATE,
    Maintenance_Schedule DATE
);
