-- QUERY: 3
SELECT 
    SUM(CASE WHEN SERVICE_NAME = 'Membership' THEN AMOUNT ELSE 0 END) AS MEMBERSHIP_REVENUE,
    SUM(CASE WHEN SERVICE_NAME = 'Class Booking' THEN AMOUNT ELSE 0 END) AS CLASS_REVENUE,
    SUM(CASE WHEN SERVICE_NAME = 'Personal Training' THEN AMOUNT ELSE 0 END) AS PST_REVENUE,
    SUM(CASE WHEN SERVICE_NAME IN ('Membership', 'Class Booking', 'Personal Training') THEN AMOUNT ELSE 0 END) AS TOTAL_REVENUE
FROM BILLING;

-- QUERY: 4
SELECT PTS.TRAINER_ID, ST.FIRST_NAME || ' ' || ST.LAST_NAME AS TRAINER_NAME, COUNT(PTS.TRAINING_ID) AS SESSIONS_TAKEN
FROM PERSONAL_TRAINING_SESSIONS PTS
JOIN STAFF ST
ON PTS.TRAINER_ID = ST.STAFF_ID
GROUP BY PTS.TRAINER_ID, ST.FIRST_NAME, ST.LAST_NAME
ORDER BY SESSIONS_TAKEN DESC, TRAINER_NAME
FETCH FIRST 5 ROWS ONLY;
