ALTER TABLE CLIENTS_GUESTS
ADD CONSTRAINT fk_member
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID);

ALTER TABLE GYM_ATTENDANCE
ADD CONSTRAINT fk_member_attendance
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID);

ALTER TABLE PAYMENTS
ADD CONSTRAINT fk_member_payments
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID);

ALTER TABLE MEMBERSHIP
ADD CONSTRAINT fk_plan_membership
FOREIGN KEY (PLAN_ID) REFERENCES MEMBERSHIP_PLANS(PLAN_ID);

ALTER TABLE PERSONAL_TRAINING_SESSIONS
ADD CONSTRAINT fk_member_training
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID);

ALTER TABLE PERSONAL_TRAINING_SESSIONS
ADD CONSTRAINT fk_trainer
FOREIGN KEY (TRAINER_ID) REFERENCES STAFF(STAFF_ID);

ALTER TABLE FITNESS_CLASS
ADD CONSTRAINT fk_centre_class
FOREIGN KEY (CENTRE_ID) REFERENCES FITNESS_CENTRE(CENTRE_ID);

ALTER TABLE FITNESS_CLASS
ADD CONSTRAINT fk_staff_class
FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID);

ALTER TABLE WORKSHOPS
ADD CONSTRAINT fk_member_workshop
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID);

ALTER TABLE WORKSHOPS
ADD CONSTRAINT fk_instructor
FOREIGN KEY (INSTRUCTOR_ID) REFERENCES STAFF(STAFF_ID);

ALTER TABLE WORKSHOPS
ADD CONSTRAINT fk_centre_workshop
FOREIGN KEY (CENTRE_ID) REFERENCES FITNESS_CENTRE(CENTRE_ID);

ALTER TABLE GYM_ATTENDANCE
ADD CONSTRAINT fk_centre_attendance
FOREIGN KEY (CENTRE_ID) REFERENCES FITNESS_CENTRE(CENTRE_ID);

ALTER TABLE EQUIPMENT_RENTAL
ADD CONSTRAINT fk_equipment
FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENT_RENTAL(EQUIPMENT_ID);
